# Generated by Django 3.1.8 on 2021-07-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210701_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_suspension',
            field=models.BooleanField(default=False),
        ),
    ]
