# Generated by Django 3.1.8 on 2021-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_has_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_confirmed_pickup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
