# Generated by Django 3.1.8 on 2021-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210701_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
